version: '3'

services:
    database:
        image: postgres:11-alpine
        ports:
            -  '5432:5432'
        volumes:
            - ./postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
